# Generated by Django 3.2.16 on 2022-11-18 21:06

from django.db import migrations, models
import sisulu.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human readable name for the domain.', max_length=128, unique=True)),
                ('address', models.CharField(help_text='The address to connect to for the domain. Can be a single instance, or the domain as a whole.', max_length=128)),
                ('search_base', models.CharField(blank=True, help_text='Optional dn in the domain to start searches from. If not supplied, then searches will be performed from the root of the domain.', max_length=255)),
                ('user_dns', models.JSONField(default=list, help_text='List of DNs in which user searches will be performed.')),
                ('group_dns', models.JSONField(default=list, help_text='List of DNs in which group searches will be performed.')),
                ('bind_dn', models.CharField(help_text='DN of the user which will be used to bind ot the domain.', max_length=255)),
                ('bind_credential', sisulu.fields.EncryptedCharField(help_text='Password used when binding to the domain.', key=b'cjrzDQRuWipNpgJuzQOvJ22pGVfNLq9IffI6DHHURlw=', max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
