# Generated by Django 3.2.16 on 2022-11-25 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sisulu.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dn', models.CharField(help_text='The distinguished name of the container', max_length=250)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['dn'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human readable name for the domain.', max_length=150, unique=True)),
                ('host', models.CharField(help_text='The address to connect to for the domain. Can be a single instance, or the domain as a whole.', max_length=150)),
                ('port', models.IntegerField(help_text='The port to connect to the domain on.')),
                ('use_ssl', models.BooleanField(default=True, help_text='Whether to encrypt communication with the domain.')),
                ('search_base', models.CharField(blank=True, help_text='Optional dn in the domain to start searches from. If not supplied, then searches will be performed from the root of the domain.', max_length=250)),
                ('bind_user_dn', models.CharField(blank=True, help_text='DN of the user which will be used to bind to the domain.', max_length=250)),
                ('bind_user_password', sisulu.fields.EncryptedCharField(blank=True, help_text='Password used when binding to the domain.', key=b'cjrzDQRuWipNpgJuzQOvJ22pGVfNLq9IffI6DHHURlw=', max_length=250)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name for this type of user.', max_length=250)),
                ('read_filters', models.TextField(blank=True, help_text='LDAP filters to apply when reading users.')),
                ('read_containers', models.ManyToManyField(blank=True, related_name='reading_user_types', to='ldap.Container')),
                ('write_containers', models.ForeignKey(blank=True, help_text='Containers into which users of this type will be written.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='writing_user_types', to='ldap.container')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserDomainLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('containers', models.ManyToManyField(help_text='Domain containers in which the user exists', related_name='user_links', to='ldap.Container')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_links', to=settings.AUTH_USER_MODEL)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_links', to='ldap.usertype')),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name for this type of group.', max_length=250)),
                ('read_filters', models.TextField(blank=True, help_text='LDAP filters to apply when reading groups.')),
                ('read_containers', models.ManyToManyField(blank=True, related_name='reading_group_types', to='ldap.Container')),
                ('write_containers', models.ForeignKey(blank=True, help_text='Containers into which group of this type will be written.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='writing_group_types', to='ldap.container')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupDomainLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('containers', models.ManyToManyField(help_text='Domain containers in which the group exists', related_name='group_links', to='ldap.Container')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_links', to='auth.group')),
                ('group_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_links', to='ldap.grouptype')),
            ],
            options={
                'ordering': ['group'],
            },
        ),
        migrations.AddField(
            model_name='container',
            name='domain',
            field=models.ForeignKey(help_text='The domain which the container belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='containers', to='ldap.domain'),
        ),
    ]
