# Generated by Django 3.2.16 on 2022-11-18 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ldap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='group_dns',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='user_dns',
        ),
        migrations.CreateModel(
            name='AccountTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human readable name for the account type.', max_length=128)),
                ('dns', models.JSONField(blank=True, default=list, help_text='List of DNs in which accounts of the type can be found')),
                ('default_dn', models.CharField(help_text='Default DN in which accounts of this type will be created', max_length=256)),
                ('domain', models.ForeignKey(help_text='The domain to which the account type belongs', on_delete=django.db.models.deletion.PROTECT, related_name='account_types', to='ldap.domain')),
            ],
        ),
    ]
