version: '3.9'

services:
  identity-ldap-server:
    container_name: identity-ldap-server
    image: bitnami/openldap:2.6
    ports:
      - '${HOST_LDAP_PORT:-1389}:1389'
    environment:
      - LDAP_LOGLEVEL=-1
    volumes:
      - './development:/ldifs:r'
      - '${HOST_LDAP_DATA_PATH:-./development/ldap_data}:/bitnami/openldap'