version: '3.9'

services:
  identity-ldap-server:
    container_name: identity-ldap-server
    image: bitnami/openldap:2.6
    ports:
      - '${HOST_LDAPS_PORT:-636}:1636'
      - '${HOST_LDAP_PORT:-389}:1389'
    environment:
      - LDAP_ADMIN_USERNAME=${LDAP_ADMIN_USERNAME}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_ROOT=${LDAP_ROOT:-dc=test,dc=com}
    volumes:
      - '${HOST_LDAP_DATA_PATH:-~/data/ldap_data}:/bitnami/openldap'
    user: '${LDAP_USER:-root}'