# Generated by Django 3.2.16 on 2022-12-09 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name for this organization', max_length=150, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the relationship', max_length=250)),
                ('groups', models.ManyToManyField(blank=True, help_text='Groups which users with an active relationship of this instance will be added to', related_name='relationships', to='auth.Group')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_on', models.DateField(blank=True, help_text='The first day on which this relationship is considered active on', null=True)),
                ('ends_after', models.DateField(blank=True, help_text='The last day which this relationship is active for', null=True)),
                ('position', models.CharField(help_text='A customized name for this position', max_length=250)),
                ('relationship', models.ForeignKey(help_text='The relationship which the user is a member of', on_delete=django.db.models.deletion.CASCADE, related_name='user_relationships', to='organizations.relationship')),
                ('user', models.ForeignKey(help_text='The user who this membership applies to', on_delete=django.db.models.deletion.CASCADE, related_name='user_relationships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['starts_on'],
            },
        ),
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this type of relationship', max_length=250)),
                ('organization', models.ForeignKey(help_text='The organization to which this relationship type belongs', on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
